package galaxy

import (
	"strings"
	"testing"

	"github.com/samber/lo"
	"github.com/stretchr/testify/assert"
)

func TestSolve1(t *testing.T) {
	input := `...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`
	assert.Equal(t, 374, lo.Must(Solve1(strings.NewReader(input))))
}

func TestParseUniverse(t *testing.T) {
	input := `...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`
	univ := ParseUniverse(strings.NewReader(input))
	assert.Len(t, univ.Galaxies, 9, univ)
	assert.Equal(t, 13, univ.Width)
	assert.Equal(t, 12, univ.Height)
}

func TestExpand(t *testing.T) {
	input := `...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`
	expected := `....#........
.........#...
#............
.............
.............
........#....
.#...........
............#
.............
.............
.........#...
#....#.......`
	assert.Equal(t, expected, strings.Join(expand(strings.Split(input, "\n")), "\n"))
}
